project_id = "zcvahuqajqqvodtezqth"

[functions.engine-ai]
verify_jwt = false

[functions.create-engine-payment]
verify_jwt = false

[functions.verify-engine-payment]
verify_jwt = false

[functions.create-scheduler-subscription]
verify_jwt = false

[functions.create-billing-portal-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

