/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrainRouteImport } from './routes/brain'
import { Route as EngineRouteImport } from './routes/engine'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAgentRouteRouteImport } from './routes/_authenticated/agent/route'
import { Route as AuthenticatedAutomationsRouteImport } from './routes/_authenticated/automations'
import { Route as AuthenticatedBankRouteImport } from './routes/_authenticated/bank'
import { Route as AuthenticatedBrandAssetsRouteImport } from './routes/_authenticated/brand-assets'
import { Route as AuthenticatedBuildMarketingRouteImport } from './routes/_authenticated/build-marketing'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedCampaignPostsRouteImport } from './routes/_authenticated/campaign-posts'
import { Route as AuthenticatedCaptionVariatorRouteImport } from './routes/_authenticated/caption-variator'
import { Route as AuthenticatedCompetitorsRouteImport } from './routes/_authenticated/competitors'
import { Route as AuthenticatedConnectRouteImport } from './routes/_authenticated/connect'
import { Route as AuthenticatedContentPlanRouteImport } from './routes/_authenticated/content-plan'
import { Route as AuthenticatedDirectorRouteImport } from './routes/_authenticated/director'
import { Route as AuthenticatedFirstPostRouteImport } from './routes/_authenticated/first-post'
import { Route as AuthenticatedFunnelRouteImport } from './routes/_authenticated/funnel'
import { Route as AuthenticatedHashtagsRouteImport } from './routes/_authenticated/hashtags'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedIdeasRouteImport } from './routes/_authenticated/ideas'
import { Route as AuthenticatedImageRouteImport } from './routes/_authenticated/image'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedMagnetRouteImport } from './routes/_authenticated/magnet'
import { Route as AuthenticatedPersonasRouteImport } from './routes/_authenticated/personas'
import { Route as AuthenticatedPlanRouteImport } from './routes/_authenticated/plan'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedRepurposeRouteImport } from './routes/_authenticated/repurpose'
import { Route as AuthenticatedSchedulerRouteImport } from './routes/_authenticated/scheduler'
import { Route as AuthenticatedSnippetsRouteImport } from './routes/_authenticated/snippets'
import { Route as AuthenticatedToolsRouteImport } from './routes/_authenticated/tools'
import { Route as AuthenticatedTrendsRouteImport } from './routes/_authenticated/trends'
import { Route as AuthenticatedWelcomeRouteImport } from './routes/_authenticated/welcome'
import { Route as ApiAgentGoalRouteImport } from './routes/api/agent-goal'
import { Route as ApiPostImageRouteImport } from './routes/api/post-image'
import { Route as GuideCampaignIdRouteImport } from './routes/guide.$campaignId'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedAdminCodesRouteImport } from './routes/_authenticated/admin.codes'
import { Route as AuthenticatedAgentIndexRouteImport } from './routes/_authenticated/agent/index'
import { Route as AuthenticatedAgentAnalyticsRouteImport } from './routes/_authenticated/agent/analytics'
import { Route as AuthenticatedAgentApprovalsRouteImport } from './routes/_authenticated/agent/approvals'
import { Route as AuthenticatedAgentCalendarRouteImport } from './routes/_authenticated/agent/calendar'
import { Route as AuthenticatedAgentGoalsRouteImport } from './routes/_authenticated/agent/goals'
import { Route as AuthenticatedAgentQueueRouteImport } from './routes/_authenticated/agent/queue'
import { Route as AuthenticatedAgentSettingsRouteImport } from './routes/_authenticated/agent/settings'
import { Route as AuthenticatedAnalyticsCampaignsRouteImport } from './routes/_authenticated/analytics.campaigns'
import { Route as AuthenticatedAnalyticsContentRouteImport } from './routes/_authenticated/analytics.content'
import { Route as AuthenticatedAnalyticsLeadsRouteImport } from './routes/_authenticated/analytics.leads'
import { Route as AuthenticatedBrainSetupRouteImport } from './routes/_authenticated/brain.setup'
import { Route as AuthenticatedCampaignIndexRouteImport } from './routes/_authenticated/campaign.index'
import { Route as AuthenticatedCampaignIdRouteImport } from './routes/_authenticated/campaign.$id'
import { Route as AuthenticatedEmailIndexRouteImport } from './routes/_authenticated/email.index'
import { Route as AuthenticatedEmailIdRouteImport } from './routes/_authenticated/email.$id'
import { Route as AuthenticatedLandingIndexRouteImport } from './routes/_authenticated/landing.index'
import { Route as AuthenticatedLandingIdRouteImport } from './routes/_authenticated/landing.$id'
import { Route as ApiPublicCompetitorScanRouteImport } from './routes/api/public/competitor-scan'
import { Route as ApiPublicEmbedLeadRouteImport } from './routes/api/public/embed-lead'
import { Route as ApiPublicEmbedDotjsRouteImport } from './routes/api/public/embed[.]js'
import { Route as ApiPublicGojiberryLeadRouteImport } from './routes/api/public/gojiberry-lead'
import { Route as ApiPublicMembershipEmailRouteImport } from './routes/api/public/membership-email'
import { Route as ApiPublicTrendScanRouteImport } from './routes/api/public/trend-scan'
import { Route as ApiPublicZernioMetricsRouteImport } from './routes/api/public/zernio-metrics'
import { Route as LovableEmailEventsRouteImport } from './routes/lovable/email/events'
import { Route as ApiPublicCronAgentRunRouteImport } from './routes/api/public/cron/agent-run'
import { Route as ApiPublicCronFoundingReminderRouteImport } from './routes/api/public/cron/founding-reminder'
import { Route as ApiPublicCronLeadSweepRouteImport } from './routes/api/public/cron/lead-sweep'
import { Route as ApiPublicCronPublishRouteImport } from './routes/api/public/cron/publish'
import { Route as ApiPublicOauthCallbackRouteImport } from './routes/api/public/oauth/callback'
import { Route as ApiPublicWebhooksMetaRouteImport } from './routes/api/public/webhooks/meta'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainRoute = BrainRouteImport.update({
  id: '/brain',
  path: '/brain',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineRoute = EngineRouteImport.update({
  id: '/engine',
  path: '/engine',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentRouteRoute = AuthenticatedAgentRouteRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutomationsRoute =
  AuthenticatedAutomationsRouteImport.update({
    id: '/automations',
    path: '/automations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBankRoute = AuthenticatedBankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandAssetsRoute =
  AuthenticatedBrandAssetsRouteImport.update({
    id: '/brand-assets',
    path: '/brand-assets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuildMarketingRoute =
  AuthenticatedBuildMarketingRouteImport.update({
    id: '/build-marketing',
    path: '/build-marketing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignPostsRoute =
  AuthenticatedCampaignPostsRouteImport.update({
    id: '/campaign-posts',
    path: '/campaign-posts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCaptionVariatorRoute =
  AuthenticatedCaptionVariatorRouteImport.update({
    id: '/caption-variator',
    path: '/caption-variator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCompetitorsRoute =
  AuthenticatedCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConnectRoute = AuthenticatedConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContentPlanRoute =
  AuthenticatedContentPlanRouteImport.update({
    id: '/content-plan',
    path: '/content-plan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDirectorRoute = AuthenticatedDirectorRouteImport.update({
  id: '/director',
  path: '/director',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFirstPostRoute = AuthenticatedFirstPostRouteImport.update({
  id: '/first-post',
  path: '/first-post',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFunnelRoute = AuthenticatedFunnelRouteImport.update({
  id: '/funnel',
  path: '/funnel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHashtagsRoute = AuthenticatedHashtagsRouteImport.update({
  id: '/hashtags',
  path: '/hashtags',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdeasRoute = AuthenticatedIdeasRouteImport.update({
  id: '/ideas',
  path: '/ideas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImageRoute = AuthenticatedImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMagnetRoute = AuthenticatedMagnetRouteImport.update({
  id: '/magnet',
  path: '/magnet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonasRoute = AuthenticatedPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanRoute = AuthenticatedPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRepurposeRoute = AuthenticatedRepurposeRouteImport.update({
  id: '/repurpose',
  path: '/repurpose',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSchedulerRoute = AuthenticatedSchedulerRouteImport.update({
  id: '/scheduler',
  path: '/scheduler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSnippetsRoute = AuthenticatedSnippetsRouteImport.update({
  id: '/snippets',
  path: '/snippets',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToolsRoute = AuthenticatedToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrendsRoute = AuthenticatedTrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWelcomeRoute = AuthenticatedWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAgentGoalRoute = ApiAgentGoalRouteImport.update({
  id: '/api/agent-goal',
  path: '/api/agent-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPostImageRoute = ApiPostImageRouteImport.update({
  id: '/api/post-image',
  path: '/api/post-image',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideCampaignIdRoute = GuideCampaignIdRouteImport.update({
  id: '/guide/$campaignId',
  path: '/guide/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminCodesRoute = AuthenticatedAdminCodesRouteImport.update({
  id: '/admin/codes',
  path: '/admin/codes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgentIndexRoute = AuthenticatedAgentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAgentRouteRoute,
} as any)
const AuthenticatedAgentAnalyticsRoute =
  AuthenticatedAgentAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAgentRouteRoute,
  } as any)
const AuthenticatedAgentApprovalsRoute =
  AuthenticatedAgentApprovalsRouteImport.update({
    id: '/approvals',
    path: '/approvals',
    getParentRoute: () => AuthenticatedAgentRouteRoute,
  } as any)
const AuthenticatedAgentCalendarRoute =
  AuthenticatedAgentCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => AuthenticatedAgentRouteRoute,
  } as any)
const AuthenticatedAgentGoalsRoute = AuthenticatedAgentGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedAgentRouteRoute,
} as any)
const AuthenticatedAgentQueueRoute = AuthenticatedAgentQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthenticatedAgentRouteRoute,
} as any)
const AuthenticatedAgentSettingsRoute =
  AuthenticatedAgentSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAgentRouteRoute,
  } as any)
const AuthenticatedAnalyticsCampaignsRoute =
  AuthenticatedAnalyticsCampaignsRouteImport.update({
    id: '/analytics/campaigns',
    path: '/analytics/campaigns',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsContentRoute =
  AuthenticatedAnalyticsContentRouteImport.update({
    id: '/analytics/content',
    path: '/analytics/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnalyticsLeadsRoute =
  AuthenticatedAnalyticsLeadsRouteImport.update({
    id: '/analytics/leads',
    path: '/analytics/leads',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrainSetupRoute = AuthenticatedBrainSetupRouteImport.update({
  id: '/brain/setup',
  path: '/brain/setup',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCampaignIndexRoute =
  AuthenticatedCampaignIndexRouteImport.update({
    id: '/campaign/',
    path: '/campaign/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCampaignIdRoute = AuthenticatedCampaignIdRouteImport.update({
  id: '/campaign/$id',
  path: '/campaign/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailIndexRoute = AuthenticatedEmailIndexRouteImport.update({
  id: '/email/',
  path: '/email/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailIdRoute = AuthenticatedEmailIdRouteImport.update({
  id: '/email/$id',
  path: '/email/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLandingIndexRoute =
  AuthenticatedLandingIndexRouteImport.update({
    id: '/landing/',
    path: '/landing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLandingIdRoute = AuthenticatedLandingIdRouteImport.update({
  id: '/landing/$id',
  path: '/landing/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicCompetitorScanRoute = ApiPublicCompetitorScanRouteImport.update({
  id: '/api/public/competitor-scan',
  path: '/api/public/competitor-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmbedLeadRoute = ApiPublicEmbedLeadRouteImport.update({
  id: '/api/public/embed-lead',
  path: '/api/public/embed-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEmbedDotjsRoute = ApiPublicEmbedDotjsRouteImport.update({
  id: '/api/public/embed.js',
  path: '/api/public/embed.js',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGojiberryLeadRoute = ApiPublicGojiberryLeadRouteImport.update({
  id: '/api/public/gojiberry-lead',
  path: '/api/public/gojiberry-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMembershipEmailRoute =
  ApiPublicMembershipEmailRouteImport.update({
    id: '/api/public/membership-email',
    path: '/api/public/membership-email',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrendScanRoute = ApiPublicTrendScanRouteImport.update({
  id: '/api/public/trend-scan',
  path: '/api/public/trend-scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZernioMetricsRoute = ApiPublicZernioMetricsRouteImport.update({
  id: '/api/public/zernio-metrics',
  path: '/api/public/zernio-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailEventsRoute = LovableEmailEventsRouteImport.update({
  id: '/lovable/email/events',
  path: '/lovable/email/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronAgentRunRoute = ApiPublicCronAgentRunRouteImport.update({
  id: '/api/public/cron/agent-run',
  path: '/api/public/cron/agent-run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronFoundingReminderRoute =
  ApiPublicCronFoundingReminderRouteImport.update({
    id: '/api/public/cron/founding-reminder',
    path: '/api/public/cron/founding-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronLeadSweepRoute = ApiPublicCronLeadSweepRouteImport.update({
  id: '/api/public/cron/lead-sweep',
  path: '/api/public/cron/lead-sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronPublishRoute = ApiPublicCronPublishRouteImport.update({
  id: '/api/public/cron/publish',
  path: '/api/public/cron/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOauthCallbackRoute = ApiPublicOauthCallbackRouteImport.update({
  id: '/api/public/oauth/callback',
  path: '/api/public/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksMetaRoute = ApiPublicWebhooksMetaRouteImport.update({
  id: '/api/public/webhooks/meta',
  path: '/api/public/webhooks/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brain': typeof BrainRoute
  '/engine': typeof EngineRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/agent': typeof AuthenticatedAgentRouteRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/bank': typeof AuthenticatedBankRoute
  '/brand-assets': typeof AuthenticatedBrandAssetsRoute
  '/build-marketing': typeof AuthenticatedBuildMarketingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/campaign-posts': typeof AuthenticatedCampaignPostsRoute
  '/caption-variator': typeof AuthenticatedCaptionVariatorRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/content-plan': typeof AuthenticatedContentPlanRoute
  '/director': typeof AuthenticatedDirectorRoute
  '/first-post': typeof AuthenticatedFirstPostRoute
  '/funnel': typeof AuthenticatedFunnelRoute
  '/hashtags': typeof AuthenticatedHashtagsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/ideas': typeof AuthenticatedIdeasRoute
  '/image': typeof AuthenticatedImageRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/magnet': typeof AuthenticatedMagnetRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/repurpose': typeof AuthenticatedRepurposeRoute
  '/scheduler': typeof AuthenticatedSchedulerRoute
  '/snippets': typeof AuthenticatedSnippetsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/api/agent-goal': typeof ApiAgentGoalRoute
  '/api/post-image': typeof ApiPostImageRoute
  '/guide/$campaignId': typeof GuideCampaignIdRoute
  '/p/$slug': typeof PSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/agent/analytics': typeof AuthenticatedAgentAnalyticsRoute
  '/agent/approvals': typeof AuthenticatedAgentApprovalsRoute
  '/agent/calendar': typeof AuthenticatedAgentCalendarRoute
  '/agent/goals': typeof AuthenticatedAgentGoalsRoute
  '/agent/queue': typeof AuthenticatedAgentQueueRoute
  '/agent/settings': typeof AuthenticatedAgentSettingsRoute
  '/analytics/campaigns': typeof AuthenticatedAnalyticsCampaignsRoute
  '/analytics/content': typeof AuthenticatedAnalyticsContentRoute
  '/analytics/leads': typeof AuthenticatedAnalyticsLeadsRoute
  '/brain/setup': typeof AuthenticatedBrainSetupRoute
  '/campaign/$id': typeof AuthenticatedCampaignIdRoute
  '/email/$id': typeof AuthenticatedEmailIdRoute
  '/landing/$id': typeof AuthenticatedLandingIdRoute
  '/api/public/competitor-scan': typeof ApiPublicCompetitorScanRoute
  '/api/public/embed-lead': typeof ApiPublicEmbedLeadRoute
  '/api/public/embed.js': typeof ApiPublicEmbedDotjsRoute
  '/api/public/gojiberry-lead': typeof ApiPublicGojiberryLeadRoute
  '/api/public/membership-email': typeof ApiPublicMembershipEmailRoute
  '/api/public/trend-scan': typeof ApiPublicTrendScanRoute
  '/api/public/zernio-metrics': typeof ApiPublicZernioMetricsRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/agent/': typeof AuthenticatedAgentIndexRoute
  '/campaign/': typeof AuthenticatedCampaignIndexRoute
  '/email/': typeof AuthenticatedEmailIndexRoute
  '/landing/': typeof AuthenticatedLandingIndexRoute
  '/api/public/cron/agent-run': typeof ApiPublicCronAgentRunRoute
  '/api/public/cron/founding-reminder': typeof ApiPublicCronFoundingReminderRoute
  '/api/public/cron/lead-sweep': typeof ApiPublicCronLeadSweepRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/oauth/callback': typeof ApiPublicOauthCallbackRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/brain': typeof BrainRoute
  '/engine': typeof EngineRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/account': typeof AuthenticatedAccountRoute
  '/automations': typeof AuthenticatedAutomationsRoute
  '/bank': typeof AuthenticatedBankRoute
  '/brand-assets': typeof AuthenticatedBrandAssetsRoute
  '/build-marketing': typeof AuthenticatedBuildMarketingRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/campaign-posts': typeof AuthenticatedCampaignPostsRoute
  '/caption-variator': typeof AuthenticatedCaptionVariatorRoute
  '/competitors': typeof AuthenticatedCompetitorsRoute
  '/connect': typeof AuthenticatedConnectRoute
  '/content-plan': typeof AuthenticatedContentPlanRoute
  '/director': typeof AuthenticatedDirectorRoute
  '/first-post': typeof AuthenticatedFirstPostRoute
  '/funnel': typeof AuthenticatedFunnelRoute
  '/hashtags': typeof AuthenticatedHashtagsRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/ideas': typeof AuthenticatedIdeasRoute
  '/image': typeof AuthenticatedImageRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/magnet': typeof AuthenticatedMagnetRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/plan': typeof AuthenticatedPlanRoute
  '/projects': typeof AuthenticatedProjectsRoute
  '/repurpose': typeof AuthenticatedRepurposeRoute
  '/scheduler': typeof AuthenticatedSchedulerRoute
  '/snippets': typeof AuthenticatedSnippetsRoute
  '/tools': typeof AuthenticatedToolsRoute
  '/trends': typeof AuthenticatedTrendsRoute
  '/welcome': typeof AuthenticatedWelcomeRoute
  '/api/agent-goal': typeof ApiAgentGoalRoute
  '/api/post-image': typeof ApiPostImageRoute
  '/guide/$campaignId': typeof GuideCampaignIdRoute
  '/p/$slug': typeof PSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/agent/analytics': typeof AuthenticatedAgentAnalyticsRoute
  '/agent/approvals': typeof AuthenticatedAgentApprovalsRoute
  '/agent/calendar': typeof AuthenticatedAgentCalendarRoute
  '/agent/goals': typeof AuthenticatedAgentGoalsRoute
  '/agent/queue': typeof AuthenticatedAgentQueueRoute
  '/agent/settings': typeof AuthenticatedAgentSettingsRoute
  '/analytics/campaigns': typeof AuthenticatedAnalyticsCampaignsRoute
  '/analytics/content': typeof AuthenticatedAnalyticsContentRoute
  '/analytics/leads': typeof AuthenticatedAnalyticsLeadsRoute
  '/brain/setup': typeof AuthenticatedBrainSetupRoute
  '/campaign/$id': typeof AuthenticatedCampaignIdRoute
  '/email/$id': typeof AuthenticatedEmailIdRoute
  '/landing/$id': typeof AuthenticatedLandingIdRoute
  '/api/public/competitor-scan': typeof ApiPublicCompetitorScanRoute
  '/api/public/embed-lead': typeof ApiPublicEmbedLeadRoute
  '/api/public/embed.js': typeof ApiPublicEmbedDotjsRoute
  '/api/public/gojiberry-lead': typeof ApiPublicGojiberryLeadRoute
  '/api/public/membership-email': typeof ApiPublicMembershipEmailRoute
  '/api/public/trend-scan': typeof ApiPublicTrendScanRoute
  '/api/public/zernio-metrics': typeof ApiPublicZernioMetricsRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/agent': typeof AuthenticatedAgentIndexRoute
  '/campaign': typeof AuthenticatedCampaignIndexRoute
  '/email': typeof AuthenticatedEmailIndexRoute
  '/landing': typeof AuthenticatedLandingIndexRoute
  '/api/public/cron/agent-run': typeof ApiPublicCronAgentRunRoute
  '/api/public/cron/founding-reminder': typeof ApiPublicCronFoundingReminderRoute
  '/api/public/cron/lead-sweep': typeof ApiPublicCronLeadSweepRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/oauth/callback': typeof ApiPublicOauthCallbackRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/brain': typeof BrainRoute
  '/engine': typeof EngineRoute
  '/mcp': typeof McpRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/waitlist': typeof WaitlistRoute
  '/_authenticated/agent': typeof AuthenticatedAgentRouteRouteWithChildren
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/automations': typeof AuthenticatedAutomationsRoute
  '/_authenticated/bank': typeof AuthenticatedBankRoute
  '/_authenticated/brand-assets': typeof AuthenticatedBrandAssetsRoute
  '/_authenticated/build-marketing': typeof AuthenticatedBuildMarketingRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/campaign-posts': typeof AuthenticatedCampaignPostsRoute
  '/_authenticated/caption-variator': typeof AuthenticatedCaptionVariatorRoute
  '/_authenticated/competitors': typeof AuthenticatedCompetitorsRoute
  '/_authenticated/connect': typeof AuthenticatedConnectRoute
  '/_authenticated/content-plan': typeof AuthenticatedContentPlanRoute
  '/_authenticated/director': typeof AuthenticatedDirectorRoute
  '/_authenticated/first-post': typeof AuthenticatedFirstPostRoute
  '/_authenticated/funnel': typeof AuthenticatedFunnelRoute
  '/_authenticated/hashtags': typeof AuthenticatedHashtagsRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/ideas': typeof AuthenticatedIdeasRoute
  '/_authenticated/image': typeof AuthenticatedImageRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/magnet': typeof AuthenticatedMagnetRoute
  '/_authenticated/personas': typeof AuthenticatedPersonasRoute
  '/_authenticated/plan': typeof AuthenticatedPlanRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRoute
  '/_authenticated/repurpose': typeof AuthenticatedRepurposeRoute
  '/_authenticated/scheduler': typeof AuthenticatedSchedulerRoute
  '/_authenticated/snippets': typeof AuthenticatedSnippetsRoute
  '/_authenticated/tools': typeof AuthenticatedToolsRoute
  '/_authenticated/trends': typeof AuthenticatedTrendsRoute
  '/_authenticated/welcome': typeof AuthenticatedWelcomeRoute
  '/api/agent-goal': typeof ApiAgentGoalRoute
  '/api/post-image': typeof ApiPostImageRoute
  '/guide/$campaignId': typeof GuideCampaignIdRoute
  '/p/$slug': typeof PSlugRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/_authenticated/agent/analytics': typeof AuthenticatedAgentAnalyticsRoute
  '/_authenticated/agent/approvals': typeof AuthenticatedAgentApprovalsRoute
  '/_authenticated/agent/calendar': typeof AuthenticatedAgentCalendarRoute
  '/_authenticated/agent/goals': typeof AuthenticatedAgentGoalsRoute
  '/_authenticated/agent/queue': typeof AuthenticatedAgentQueueRoute
  '/_authenticated/agent/settings': typeof AuthenticatedAgentSettingsRoute
  '/_authenticated/analytics/campaigns': typeof AuthenticatedAnalyticsCampaignsRoute
  '/_authenticated/analytics/content': typeof AuthenticatedAnalyticsContentRoute
  '/_authenticated/analytics/leads': typeof AuthenticatedAnalyticsLeadsRoute
  '/_authenticated/brain/setup': typeof AuthenticatedBrainSetupRoute
  '/_authenticated/campaign/$id': typeof AuthenticatedCampaignIdRoute
  '/_authenticated/email/$id': typeof AuthenticatedEmailIdRoute
  '/_authenticated/landing/$id': typeof AuthenticatedLandingIdRoute
  '/api/public/competitor-scan': typeof ApiPublicCompetitorScanRoute
  '/api/public/embed-lead': typeof ApiPublicEmbedLeadRoute
  '/api/public/embed.js': typeof ApiPublicEmbedDotjsRoute
  '/api/public/gojiberry-lead': typeof ApiPublicGojiberryLeadRoute
  '/api/public/membership-email': typeof ApiPublicMembershipEmailRoute
  '/api/public/trend-scan': typeof ApiPublicTrendScanRoute
  '/api/public/zernio-metrics': typeof ApiPublicZernioMetricsRoute
  '/lovable/email/events': typeof LovableEmailEventsRoute
  '/_authenticated/agent/': typeof AuthenticatedAgentIndexRoute
  '/_authenticated/campaign/': typeof AuthenticatedCampaignIndexRoute
  '/_authenticated/email/': typeof AuthenticatedEmailIndexRoute
  '/_authenticated/landing/': typeof AuthenticatedLandingIndexRoute
  '/api/public/cron/agent-run': typeof ApiPublicCronAgentRunRoute
  '/api/public/cron/founding-reminder': typeof ApiPublicCronFoundingReminderRoute
  '/api/public/cron/lead-sweep': typeof ApiPublicCronLeadSweepRoute
  '/api/public/cron/publish': typeof ApiPublicCronPublishRoute
  '/api/public/oauth/callback': typeof ApiPublicOauthCallbackRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/brain'
    | '/engine'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/waitlist'
    | '/agent'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/automations'
    | '/bank'
    | '/brand-assets'
    | '/build-marketing'
    | '/calendar'
    | '/campaign-posts'
    | '/caption-variator'
    | '/competitors'
    | '/connect'
    | '/content-plan'
    | '/director'
    | '/first-post'
    | '/funnel'
    | '/hashtags'
    | '/history'
    | '/home'
    | '/ideas'
    | '/image'
    | '/leads'
    | '/magnet'
    | '/personas'
    | '/plan'
    | '/projects'
    | '/repurpose'
    | '/scheduler'
    | '/snippets'
    | '/tools'
    | '/trends'
    | '/welcome'
    | '/api/agent-goal'
    | '/api/post-image'
    | '/guide/$campaignId'
    | '/p/$slug'
    | '/.lovable/oauth/consent'
    | '/admin/codes'
    | '/agent/analytics'
    | '/agent/approvals'
    | '/agent/calendar'
    | '/agent/goals'
    | '/agent/queue'
    | '/agent/settings'
    | '/analytics/campaigns'
    | '/analytics/content'
    | '/analytics/leads'
    | '/brain/setup'
    | '/campaign/$id'
    | '/email/$id'
    | '/landing/$id'
    | '/api/public/competitor-scan'
    | '/api/public/embed-lead'
    | '/api/public/embed.js'
    | '/api/public/gojiberry-lead'
    | '/api/public/membership-email'
    | '/api/public/trend-scan'
    | '/api/public/zernio-metrics'
    | '/lovable/email/events'
    | '/agent/'
    | '/campaign/'
    | '/email/'
    | '/landing/'
    | '/api/public/cron/agent-run'
    | '/api/public/cron/founding-reminder'
    | '/api/public/cron/lead-sweep'
    | '/api/public/cron/publish'
    | '/api/public/oauth/callback'
    | '/api/public/webhooks/meta'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/brain'
    | '/engine'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/waitlist'
    | '/.well-known/oauth-protected-resource'
    | '/account'
    | '/automations'
    | '/bank'
    | '/brand-assets'
    | '/build-marketing'
    | '/calendar'
    | '/campaign-posts'
    | '/caption-variator'
    | '/competitors'
    | '/connect'
    | '/content-plan'
    | '/director'
    | '/first-post'
    | '/funnel'
    | '/hashtags'
    | '/history'
    | '/home'
    | '/ideas'
    | '/image'
    | '/leads'
    | '/magnet'
    | '/personas'
    | '/plan'
    | '/projects'
    | '/repurpose'
    | '/scheduler'
    | '/snippets'
    | '/tools'
    | '/trends'
    | '/welcome'
    | '/api/agent-goal'
    | '/api/post-image'
    | '/guide/$campaignId'
    | '/p/$slug'
    | '/.lovable/oauth/consent'
    | '/admin/codes'
    | '/agent/analytics'
    | '/agent/approvals'
    | '/agent/calendar'
    | '/agent/goals'
    | '/agent/queue'
    | '/agent/settings'
    | '/analytics/campaigns'
    | '/analytics/content'
    | '/analytics/leads'
    | '/brain/setup'
    | '/campaign/$id'
    | '/email/$id'
    | '/landing/$id'
    | '/api/public/competitor-scan'
    | '/api/public/embed-lead'
    | '/api/public/embed.js'
    | '/api/public/gojiberry-lead'
    | '/api/public/membership-email'
    | '/api/public/trend-scan'
    | '/api/public/zernio-metrics'
    | '/lovable/email/events'
    | '/agent'
    | '/campaign'
    | '/email'
    | '/landing'
    | '/api/public/cron/agent-run'
    | '/api/public/cron/founding-reminder'
    | '/api/public/cron/lead-sweep'
    | '/api/public/cron/publish'
    | '/api/public/oauth/callback'
    | '/api/public/webhooks/meta'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/brain'
    | '/engine'
    | '/mcp'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/waitlist'
    | '/_authenticated/agent'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/account'
    | '/_authenticated/automations'
    | '/_authenticated/bank'
    | '/_authenticated/brand-assets'
    | '/_authenticated/build-marketing'
    | '/_authenticated/calendar'
    | '/_authenticated/campaign-posts'
    | '/_authenticated/caption-variator'
    | '/_authenticated/competitors'
    | '/_authenticated/connect'
    | '/_authenticated/content-plan'
    | '/_authenticated/director'
    | '/_authenticated/first-post'
    | '/_authenticated/funnel'
    | '/_authenticated/hashtags'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/ideas'
    | '/_authenticated/image'
    | '/_authenticated/leads'
    | '/_authenticated/magnet'
    | '/_authenticated/personas'
    | '/_authenticated/plan'
    | '/_authenticated/projects'
    | '/_authenticated/repurpose'
    | '/_authenticated/scheduler'
    | '/_authenticated/snippets'
    | '/_authenticated/tools'
    | '/_authenticated/trends'
    | '/_authenticated/welcome'
    | '/api/agent-goal'
    | '/api/post-image'
    | '/guide/$campaignId'
    | '/p/$slug'
    | '/.lovable/oauth/consent'
    | '/_authenticated/admin/codes'
    | '/_authenticated/agent/analytics'
    | '/_authenticated/agent/approvals'
    | '/_authenticated/agent/calendar'
    | '/_authenticated/agent/goals'
    | '/_authenticated/agent/queue'
    | '/_authenticated/agent/settings'
    | '/_authenticated/analytics/campaigns'
    | '/_authenticated/analytics/content'
    | '/_authenticated/analytics/leads'
    | '/_authenticated/brain/setup'
    | '/_authenticated/campaign/$id'
    | '/_authenticated/email/$id'
    | '/_authenticated/landing/$id'
    | '/api/public/competitor-scan'
    | '/api/public/embed-lead'
    | '/api/public/embed.js'
    | '/api/public/gojiberry-lead'
    | '/api/public/membership-email'
    | '/api/public/trend-scan'
    | '/api/public/zernio-metrics'
    | '/lovable/email/events'
    | '/_authenticated/agent/'
    | '/_authenticated/campaign/'
    | '/_authenticated/email/'
    | '/_authenticated/landing/'
    | '/api/public/cron/agent-run'
    | '/api/public/cron/founding-reminder'
    | '/api/public/cron/lead-sweep'
    | '/api/public/cron/publish'
    | '/api/public/oauth/callback'
    | '/api/public/webhooks/meta'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BrainRoute: typeof BrainRoute
  EngineRoute: typeof EngineRoute
  McpRoute: typeof McpRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  WaitlistRoute: typeof WaitlistRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiAgentGoalRoute: typeof ApiAgentGoalRoute
  ApiPostImageRoute: typeof ApiPostImageRoute
  GuideCampaignIdRoute: typeof GuideCampaignIdRoute
  PSlugRoute: typeof PSlugRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  ApiPublicCompetitorScanRoute: typeof ApiPublicCompetitorScanRoute
  ApiPublicEmbedLeadRoute: typeof ApiPublicEmbedLeadRoute
  ApiPublicEmbedDotjsRoute: typeof ApiPublicEmbedDotjsRoute
  ApiPublicGojiberryLeadRoute: typeof ApiPublicGojiberryLeadRoute
  ApiPublicMembershipEmailRoute: typeof ApiPublicMembershipEmailRoute
  ApiPublicTrendScanRoute: typeof ApiPublicTrendScanRoute
  ApiPublicZernioMetricsRoute: typeof ApiPublicZernioMetricsRoute
  LovableEmailEventsRoute: typeof LovableEmailEventsRoute
  ApiPublicCronAgentRunRoute: typeof ApiPublicCronAgentRunRoute
  ApiPublicCronFoundingReminderRoute: typeof ApiPublicCronFoundingReminderRoute
  ApiPublicCronLeadSweepRoute: typeof ApiPublicCronLeadSweepRoute
  ApiPublicCronPublishRoute: typeof ApiPublicCronPublishRoute
  ApiPublicOauthCallbackRoute: typeof ApiPublicOauthCallbackRoute
  ApiPublicWebhooksMetaRoute: typeof ApiPublicWebhooksMetaRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brain': {
      id: '/brain'
      path: '/brain'
      fullPath: '/brain'
      preLoaderRoute: typeof BrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engine': {
      id: '/engine'
      path: '/engine'
      fullPath: '/engine'
      preLoaderRoute: typeof EngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent': {
      id: '/_authenticated/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AuthenticatedAgentRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automations': {
      id: '/_authenticated/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AuthenticatedAutomationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bank': {
      id: '/_authenticated/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof AuthenticatedBankRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brand-assets': {
      id: '/_authenticated/brand-assets'
      path: '/brand-assets'
      fullPath: '/brand-assets'
      preLoaderRoute: typeof AuthenticatedBrandAssetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/build-marketing': {
      id: '/_authenticated/build-marketing'
      path: '/build-marketing'
      fullPath: '/build-marketing'
      preLoaderRoute: typeof AuthenticatedBuildMarketingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaign-posts': {
      id: '/_authenticated/campaign-posts'
      path: '/campaign-posts'
      fullPath: '/campaign-posts'
      preLoaderRoute: typeof AuthenticatedCampaignPostsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/caption-variator': {
      id: '/_authenticated/caption-variator'
      path: '/caption-variator'
      fullPath: '/caption-variator'
      preLoaderRoute: typeof AuthenticatedCaptionVariatorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/competitors': {
      id: '/_authenticated/competitors'
      path: '/competitors'
      fullPath: '/competitors'
      preLoaderRoute: typeof AuthenticatedCompetitorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/connect': {
      id: '/_authenticated/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof AuthenticatedConnectRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/content-plan': {
      id: '/_authenticated/content-plan'
      path: '/content-plan'
      fullPath: '/content-plan'
      preLoaderRoute: typeof AuthenticatedContentPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/director': {
      id: '/_authenticated/director'
      path: '/director'
      fullPath: '/director'
      preLoaderRoute: typeof AuthenticatedDirectorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/first-post': {
      id: '/_authenticated/first-post'
      path: '/first-post'
      fullPath: '/first-post'
      preLoaderRoute: typeof AuthenticatedFirstPostRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/funnel': {
      id: '/_authenticated/funnel'
      path: '/funnel'
      fullPath: '/funnel'
      preLoaderRoute: typeof AuthenticatedFunnelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hashtags': {
      id: '/_authenticated/hashtags'
      path: '/hashtags'
      fullPath: '/hashtags'
      preLoaderRoute: typeof AuthenticatedHashtagsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ideas': {
      id: '/_authenticated/ideas'
      path: '/ideas'
      fullPath: '/ideas'
      preLoaderRoute: typeof AuthenticatedIdeasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/image': {
      id: '/_authenticated/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof AuthenticatedImageRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/magnet': {
      id: '/_authenticated/magnet'
      path: '/magnet'
      fullPath: '/magnet'
      preLoaderRoute: typeof AuthenticatedMagnetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personas': {
      id: '/_authenticated/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthenticatedPersonasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plan': {
      id: '/_authenticated/plan'
      path: '/plan'
      fullPath: '/plan'
      preLoaderRoute: typeof AuthenticatedPlanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/repurpose': {
      id: '/_authenticated/repurpose'
      path: '/repurpose'
      fullPath: '/repurpose'
      preLoaderRoute: typeof AuthenticatedRepurposeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/scheduler': {
      id: '/_authenticated/scheduler'
      path: '/scheduler'
      fullPath: '/scheduler'
      preLoaderRoute: typeof AuthenticatedSchedulerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/snippets': {
      id: '/_authenticated/snippets'
      path: '/snippets'
      fullPath: '/snippets'
      preLoaderRoute: typeof AuthenticatedSnippetsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tools': {
      id: '/_authenticated/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof AuthenticatedToolsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/trends': {
      id: '/_authenticated/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof AuthenticatedTrendsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/welcome': {
      id: '/_authenticated/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AuthenticatedWelcomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/agent-goal': {
      id: '/api/agent-goal'
      path: '/api/agent-goal'
      fullPath: '/api/agent-goal'
      preLoaderRoute: typeof ApiAgentGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/post-image': {
      id: '/api/post-image'
      path: '/api/post-image'
      fullPath: '/api/post-image'
      preLoaderRoute: typeof ApiPostImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$campaignId': {
      id: '/guide/$campaignId'
      path: '/guide/$campaignId'
      fullPath: '/guide/$campaignId'
      preLoaderRoute: typeof GuideCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/codes': {
      id: '/_authenticated/admin/codes'
      path: '/admin/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AuthenticatedAdminCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agent/': {
      id: '/_authenticated/agent/'
      path: '/'
      fullPath: '/agent/'
      preLoaderRoute: typeof AuthenticatedAgentIndexRouteImport
      parentRoute: typeof AuthenticatedAgentRouteRoute
    }
    '/_authenticated/agent/analytics': {
      id: '/_authenticated/agent/analytics'
      path: '/analytics'
      fullPath: '/agent/analytics'
      preLoaderRoute: typeof AuthenticatedAgentAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAgentRouteRoute
    }
    '/_authenticated/agent/approvals': {
      id: '/_authenticated/agent/approvals'
      path: '/approvals'
      fullPath: '/agent/approvals'
      preLoaderRoute: typeof AuthenticatedAgentApprovalsRouteImport
      parentRoute: typeof AuthenticatedAgentRouteRoute
    }
    '/_authenticated/agent/calendar': {
      id: '/_authenticated/agent/calendar'
      path: '/calendar'
      fullPath: '/agent/calendar'
      preLoaderRoute: typeof AuthenticatedAgentCalendarRouteImport
      parentRoute: typeof AuthenticatedAgentRouteRoute
    }
    '/_authenticated/agent/goals': {
      id: '/_authenticated/agent/goals'
      path: '/goals'
      fullPath: '/agent/goals'
      preLoaderRoute: typeof AuthenticatedAgentGoalsRouteImport
      parentRoute: typeof AuthenticatedAgentRouteRoute
    }
    '/_authenticated/agent/queue': {
      id: '/_authenticated/agent/queue'
      path: '/queue'
      fullPath: '/agent/queue'
      preLoaderRoute: typeof AuthenticatedAgentQueueRouteImport
      parentRoute: typeof AuthenticatedAgentRouteRoute
    }
    '/_authenticated/agent/settings': {
      id: '/_authenticated/agent/settings'
      path: '/settings'
      fullPath: '/agent/settings'
      preLoaderRoute: typeof AuthenticatedAgentSettingsRouteImport
      parentRoute: typeof AuthenticatedAgentRouteRoute
    }
    '/_authenticated/analytics/campaigns': {
      id: '/_authenticated/analytics/campaigns'
      path: '/analytics/campaigns'
      fullPath: '/analytics/campaigns'
      preLoaderRoute: typeof AuthenticatedAnalyticsCampaignsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/content': {
      id: '/_authenticated/analytics/content'
      path: '/analytics/content'
      fullPath: '/analytics/content'
      preLoaderRoute: typeof AuthenticatedAnalyticsContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics/leads': {
      id: '/_authenticated/analytics/leads'
      path: '/analytics/leads'
      fullPath: '/analytics/leads'
      preLoaderRoute: typeof AuthenticatedAnalyticsLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brain/setup': {
      id: '/_authenticated/brain/setup'
      path: '/brain/setup'
      fullPath: '/brain/setup'
      preLoaderRoute: typeof AuthenticatedBrainSetupRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaign/': {
      id: '/_authenticated/campaign/'
      path: '/campaign'
      fullPath: '/campaign/'
      preLoaderRoute: typeof AuthenticatedCampaignIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/campaign/$id': {
      id: '/_authenticated/campaign/$id'
      path: '/campaign/$id'
      fullPath: '/campaign/$id'
      preLoaderRoute: typeof AuthenticatedCampaignIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email/': {
      id: '/_authenticated/email/'
      path: '/email'
      fullPath: '/email/'
      preLoaderRoute: typeof AuthenticatedEmailIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email/$id': {
      id: '/_authenticated/email/$id'
      path: '/email/$id'
      fullPath: '/email/$id'
      preLoaderRoute: typeof AuthenticatedEmailIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing/': {
      id: '/_authenticated/landing/'
      path: '/landing'
      fullPath: '/landing/'
      preLoaderRoute: typeof AuthenticatedLandingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landing/$id': {
      id: '/_authenticated/landing/$id'
      path: '/landing/$id'
      fullPath: '/landing/$id'
      preLoaderRoute: typeof AuthenticatedLandingIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/competitor-scan': {
      id: '/api/public/competitor-scan'
      path: '/api/public/competitor-scan'
      fullPath: '/api/public/competitor-scan'
      preLoaderRoute: typeof ApiPublicCompetitorScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/embed-lead': {
      id: '/api/public/embed-lead'
      path: '/api/public/embed-lead'
      fullPath: '/api/public/embed-lead'
      preLoaderRoute: typeof ApiPublicEmbedLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/embed.js': {
      id: '/api/public/embed.js'
      path: '/api/public/embed.js'
      fullPath: '/api/public/embed.js'
      preLoaderRoute: typeof ApiPublicEmbedDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gojiberry-lead': {
      id: '/api/public/gojiberry-lead'
      path: '/api/public/gojiberry-lead'
      fullPath: '/api/public/gojiberry-lead'
      preLoaderRoute: typeof ApiPublicGojiberryLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/membership-email': {
      id: '/api/public/membership-email'
      path: '/api/public/membership-email'
      fullPath: '/api/public/membership-email'
      preLoaderRoute: typeof ApiPublicMembershipEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/trend-scan': {
      id: '/api/public/trend-scan'
      path: '/api/public/trend-scan'
      fullPath: '/api/public/trend-scan'
      preLoaderRoute: typeof ApiPublicTrendScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zernio-metrics': {
      id: '/api/public/zernio-metrics'
      path: '/api/public/zernio-metrics'
      fullPath: '/api/public/zernio-metrics'
      preLoaderRoute: typeof ApiPublicZernioMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/events': {
      id: '/lovable/email/events'
      path: '/lovable/email/events'
      fullPath: '/lovable/email/events'
      preLoaderRoute: typeof LovableEmailEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/agent-run': {
      id: '/api/public/cron/agent-run'
      path: '/api/public/cron/agent-run'
      fullPath: '/api/public/cron/agent-run'
      preLoaderRoute: typeof ApiPublicCronAgentRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/founding-reminder': {
      id: '/api/public/cron/founding-reminder'
      path: '/api/public/cron/founding-reminder'
      fullPath: '/api/public/cron/founding-reminder'
      preLoaderRoute: typeof ApiPublicCronFoundingReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/lead-sweep': {
      id: '/api/public/cron/lead-sweep'
      path: '/api/public/cron/lead-sweep'
      fullPath: '/api/public/cron/lead-sweep'
      preLoaderRoute: typeof ApiPublicCronLeadSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/publish': {
      id: '/api/public/cron/publish'
      path: '/api/public/cron/publish'
      fullPath: '/api/public/cron/publish'
      preLoaderRoute: typeof ApiPublicCronPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/callback': {
      id: '/api/public/oauth/callback'
      path: '/api/public/oauth/callback'
      fullPath: '/api/public/oauth/callback'
      preLoaderRoute: typeof ApiPublicOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/meta': {
      id: '/api/public/webhooks/meta'
      path: '/api/public/webhooks/meta'
      fullPath: '/api/public/webhooks/meta'
      preLoaderRoute: typeof ApiPublicWebhooksMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAgentRouteRouteChildren {
  AuthenticatedAgentAnalyticsRoute: typeof AuthenticatedAgentAnalyticsRoute
  AuthenticatedAgentApprovalsRoute: typeof AuthenticatedAgentApprovalsRoute
  AuthenticatedAgentCalendarRoute: typeof AuthenticatedAgentCalendarRoute
  AuthenticatedAgentGoalsRoute: typeof AuthenticatedAgentGoalsRoute
  AuthenticatedAgentQueueRoute: typeof AuthenticatedAgentQueueRoute
  AuthenticatedAgentSettingsRoute: typeof AuthenticatedAgentSettingsRoute
  AuthenticatedAgentIndexRoute: typeof AuthenticatedAgentIndexRoute
}

const AuthenticatedAgentRouteRouteChildren: AuthenticatedAgentRouteRouteChildren =
  {
    AuthenticatedAgentAnalyticsRoute: AuthenticatedAgentAnalyticsRoute,
    AuthenticatedAgentApprovalsRoute: AuthenticatedAgentApprovalsRoute,
    AuthenticatedAgentCalendarRoute: AuthenticatedAgentCalendarRoute,
    AuthenticatedAgentGoalsRoute: AuthenticatedAgentGoalsRoute,
    AuthenticatedAgentQueueRoute: AuthenticatedAgentQueueRoute,
    AuthenticatedAgentSettingsRoute: AuthenticatedAgentSettingsRoute,
    AuthenticatedAgentIndexRoute: AuthenticatedAgentIndexRoute,
  }

const AuthenticatedAgentRouteRouteWithChildren =
  AuthenticatedAgentRouteRoute._addFileChildren(
    AuthenticatedAgentRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgentRouteRoute: typeof AuthenticatedAgentRouteRouteWithChildren
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAutomationsRoute: typeof AuthenticatedAutomationsRoute
  AuthenticatedBankRoute: typeof AuthenticatedBankRoute
  AuthenticatedBrandAssetsRoute: typeof AuthenticatedBrandAssetsRoute
  AuthenticatedBuildMarketingRoute: typeof AuthenticatedBuildMarketingRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedCampaignPostsRoute: typeof AuthenticatedCampaignPostsRoute
  AuthenticatedCaptionVariatorRoute: typeof AuthenticatedCaptionVariatorRoute
  AuthenticatedCompetitorsRoute: typeof AuthenticatedCompetitorsRoute
  AuthenticatedConnectRoute: typeof AuthenticatedConnectRoute
  AuthenticatedContentPlanRoute: typeof AuthenticatedContentPlanRoute
  AuthenticatedDirectorRoute: typeof AuthenticatedDirectorRoute
  AuthenticatedFirstPostRoute: typeof AuthenticatedFirstPostRoute
  AuthenticatedFunnelRoute: typeof AuthenticatedFunnelRoute
  AuthenticatedHashtagsRoute: typeof AuthenticatedHashtagsRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIdeasRoute: typeof AuthenticatedIdeasRoute
  AuthenticatedImageRoute: typeof AuthenticatedImageRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMagnetRoute: typeof AuthenticatedMagnetRoute
  AuthenticatedPersonasRoute: typeof AuthenticatedPersonasRoute
  AuthenticatedPlanRoute: typeof AuthenticatedPlanRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRoute
  AuthenticatedRepurposeRoute: typeof AuthenticatedRepurposeRoute
  AuthenticatedSchedulerRoute: typeof AuthenticatedSchedulerRoute
  AuthenticatedSnippetsRoute: typeof AuthenticatedSnippetsRoute
  AuthenticatedToolsRoute: typeof AuthenticatedToolsRoute
  AuthenticatedTrendsRoute: typeof AuthenticatedTrendsRoute
  AuthenticatedWelcomeRoute: typeof AuthenticatedWelcomeRoute
  AuthenticatedAdminCodesRoute: typeof AuthenticatedAdminCodesRoute
  AuthenticatedAnalyticsCampaignsRoute: typeof AuthenticatedAnalyticsCampaignsRoute
  AuthenticatedAnalyticsContentRoute: typeof AuthenticatedAnalyticsContentRoute
  AuthenticatedAnalyticsLeadsRoute: typeof AuthenticatedAnalyticsLeadsRoute
  AuthenticatedBrainSetupRoute: typeof AuthenticatedBrainSetupRoute
  AuthenticatedCampaignIdRoute: typeof AuthenticatedCampaignIdRoute
  AuthenticatedEmailIdRoute: typeof AuthenticatedEmailIdRoute
  AuthenticatedLandingIdRoute: typeof AuthenticatedLandingIdRoute
  AuthenticatedCampaignIndexRoute: typeof AuthenticatedCampaignIndexRoute
  AuthenticatedEmailIndexRoute: typeof AuthenticatedEmailIndexRoute
  AuthenticatedLandingIndexRoute: typeof AuthenticatedLandingIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgentRouteRoute: AuthenticatedAgentRouteRouteWithChildren,
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAutomationsRoute: AuthenticatedAutomationsRoute,
  AuthenticatedBankRoute: AuthenticatedBankRoute,
  AuthenticatedBrandAssetsRoute: AuthenticatedBrandAssetsRoute,
  AuthenticatedBuildMarketingRoute: AuthenticatedBuildMarketingRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedCampaignPostsRoute: AuthenticatedCampaignPostsRoute,
  AuthenticatedCaptionVariatorRoute: AuthenticatedCaptionVariatorRoute,
  AuthenticatedCompetitorsRoute: AuthenticatedCompetitorsRoute,
  AuthenticatedConnectRoute: AuthenticatedConnectRoute,
  AuthenticatedContentPlanRoute: AuthenticatedContentPlanRoute,
  AuthenticatedDirectorRoute: AuthenticatedDirectorRoute,
  AuthenticatedFirstPostRoute: AuthenticatedFirstPostRoute,
  AuthenticatedFunnelRoute: AuthenticatedFunnelRoute,
  AuthenticatedHashtagsRoute: AuthenticatedHashtagsRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIdeasRoute: AuthenticatedIdeasRoute,
  AuthenticatedImageRoute: AuthenticatedImageRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMagnetRoute: AuthenticatedMagnetRoute,
  AuthenticatedPersonasRoute: AuthenticatedPersonasRoute,
  AuthenticatedPlanRoute: AuthenticatedPlanRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRoute,
  AuthenticatedRepurposeRoute: AuthenticatedRepurposeRoute,
  AuthenticatedSchedulerRoute: AuthenticatedSchedulerRoute,
  AuthenticatedSnippetsRoute: AuthenticatedSnippetsRoute,
  AuthenticatedToolsRoute: AuthenticatedToolsRoute,
  AuthenticatedTrendsRoute: AuthenticatedTrendsRoute,
  AuthenticatedWelcomeRoute: AuthenticatedWelcomeRoute,
  AuthenticatedAdminCodesRoute: AuthenticatedAdminCodesRoute,
  AuthenticatedAnalyticsCampaignsRoute: AuthenticatedAnalyticsCampaignsRoute,
  AuthenticatedAnalyticsContentRoute: AuthenticatedAnalyticsContentRoute,
  AuthenticatedAnalyticsLeadsRoute: AuthenticatedAnalyticsLeadsRoute,
  AuthenticatedBrainSetupRoute: AuthenticatedBrainSetupRoute,
  AuthenticatedCampaignIdRoute: AuthenticatedCampaignIdRoute,
  AuthenticatedEmailIdRoute: AuthenticatedEmailIdRoute,
  AuthenticatedLandingIdRoute: AuthenticatedLandingIdRoute,
  AuthenticatedCampaignIndexRoute: AuthenticatedCampaignIndexRoute,
  AuthenticatedEmailIndexRoute: AuthenticatedEmailIndexRoute,
  AuthenticatedLandingIndexRoute: AuthenticatedLandingIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BrainRoute: BrainRoute,
  EngineRoute: EngineRoute,
  McpRoute: McpRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  WaitlistRoute: WaitlistRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiAgentGoalRoute: ApiAgentGoalRoute,
  ApiPostImageRoute: ApiPostImageRoute,
  GuideCampaignIdRoute: GuideCampaignIdRoute,
  PSlugRoute: PSlugRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  ApiPublicCompetitorScanRoute: ApiPublicCompetitorScanRoute,
  ApiPublicEmbedLeadRoute: ApiPublicEmbedLeadRoute,
  ApiPublicEmbedDotjsRoute: ApiPublicEmbedDotjsRoute,
  ApiPublicGojiberryLeadRoute: ApiPublicGojiberryLeadRoute,
  ApiPublicMembershipEmailRoute: ApiPublicMembershipEmailRoute,
  ApiPublicTrendScanRoute: ApiPublicTrendScanRoute,
  ApiPublicZernioMetricsRoute: ApiPublicZernioMetricsRoute,
  LovableEmailEventsRoute: LovableEmailEventsRoute,
  ApiPublicCronAgentRunRoute: ApiPublicCronAgentRunRoute,
  ApiPublicCronFoundingReminderRoute: ApiPublicCronFoundingReminderRoute,
  ApiPublicCronLeadSweepRoute: ApiPublicCronLeadSweepRoute,
  ApiPublicCronPublishRoute: ApiPublicCronPublishRoute,
  ApiPublicOauthCallbackRoute: ApiPublicOauthCallbackRoute,
  ApiPublicWebhooksMetaRoute: ApiPublicWebhooksMetaRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
